version: '3'
services:
  app:
    build: .
    image: slobbery/app-node
    restart: on-failure
    depends_on:
      - postgres
    ports:
      - ${PORT}:${PORT}
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
    command: npm run start
    volumes:
      - ./log:/usr/app/log
      - ./src:/usr/app/src
    networks:
      - app-net

  postgres:
    build: ./database/
    image: slobbery/app-database
    restart: always
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    environment:
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DATABASE}
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.5.0/24

volumes:
  postgresdata:
